default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: comic_book_app_development

test:
  <<: *default
  database: comic_book_app_test

production:
  <<: *default
  database: comic_book_app_production
  username: <USERNAME>
  password: <%= ENV['COMIC_BOOK_APP_DATABASE_PASSWORD'] %>
